In [3]:
"""
-----------------------------------------------------------------------------
Assignment-4: Matrix computation exercise using python and numpy
-----------------------------------------------------------------------------
AUTHOR: Soumitra Samanta (soumitra.samanta@gm.rkmvu.ac.in)
-----------------------------------------------------------------------------
Package required:
Numpy: https://numpy.org/
Matplotlib: https://matplotlib.org
-----------------------------------------------------------------------------
"""

import numpy as np
from numpy.random import RandomState
from assignment_4_matrix_computation_exc import *

# for auto-reloading extenrnal modules
# see http://stackoverflow.com/questions/1907993/autoreload-of-modules-in-ipython
%load_ext autoreload
%autoreload 2


The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


# Please check the file <font color='red'>assignment_4_matrix_computation.py</font> and fillup all the functions implementation from Assignment-2 & Assignment-3.
-----------------------------------------------------------------------------

# Reduce a square matrix $A$ of order $n$ to Hermite cannonical form (HCF) by elementary row operations only. Implement your funtion as <font color='red'>reduce_to_hcf_matrix</font> started at <font color='red'>line no 735</font> in <font color='red'>assignment_4_matrix_computation.py</font> file in appropriate location. You'll find <font color='red'>assignment_4_matrix_computation.py</font> within this folder.
[20 points]

In [4]:

# Now test your code
np.random.seed(42)# for reproduce the random numbers
l = 9
n = 5
error_decimal = 10
A = np.random.randint(-l, l, (n, n))
print('A random matrices A:\n{}' .format(A))
print('-'*70)

A_hcf,  E_ops= reduce_to_hcf_matrix(A)        
print('The reduce to HCF of A:\n{}\nand\nE_ops: \n{} ' .format(np.round(A_hcf, error_decimal), np.round(E_ops, error_decimal)))
print('-'*70)   




A random matrices A:
[[-3  5  1 -2 -3]
 [ 1  1 -6 -2 -7]
 [-8  2 -4 -8 -9]
 [ 2  2  7  0  6]
 [ 5  5  2 -7 -5]]
----------------------------------------------------------------------
The reduce to HCF of A:
[[ 1.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [-0. -0. -0. -0.  1.]]
and
E_ops: 
[[-0.05698529  0.06360294 -0.05441176  0.01433824  0.06029412]
 [ 0.06801471  0.58860294  0.04558824  0.58933824 -0.23970588]
 [ 0.22058824 -0.95588235 -0.17647059 -0.92647059  0.41176471]
 [ 0.25735294 -0.44852941 -0.20588235 -0.58088235  0.14705882]
 [-0.26102941  0.89779412  0.20882353  1.04632353 -0.42058824]] 
----------------------------------------------------------------------


# Apply the above HCF method to find a soluation of a system $Ax=b$. Where $A$ is a matrix of order $m \times n$. You have to generate a random system of linear equation ($m$-equations with $n$ unknowns) and check your results. Use your previous funtion <font color='red'>generate_random_linear_system</font> to generate the linear system and implement <font color='red'>soln_m_equations_n_unknowns</font> started at <font color='red'>line no 766</font> in <font color='red'>assignment_4_matrix_computation.py</font> file in appropriate location. You'll find <font color='red'>assignment_4_matrix_computation.py</font> within this folder.
[10 points]

In [6]:
np.random.seed(42)# for reproduce the random numbers
l = 9
m = 4
n = 5
error_decimal = 10

A, b, x = generate_random_linear_system(m, n)
print('The coefficient matrix A: \n{}' .format(A))
print('-'*70) 
print('Right-hand vector b: \n{}' .format(b))
print('-'*70)
print('Actual soluation x: \n{}' .format(x))
print('-'*70)


x_est, HCF_A = soln_m_equations_n_unknowns(A, b)        
print('Estimated soluation x_est: \n{}\nand \nabsolute diff|x-x_est| upto {}-th decimal place: \n{}' .format(np.round(x_est, 3), error_decimal, np.round(np.abs(x-x_est), error_decimal)))
print('-'*70)      






The coefficient matrix A: 
[[-3.  5.  1. -2. -3.]
 [ 9.  1.  1. -6. -2.]
 [-7. -8.  2. -4. -8.]
 [-9.  2.  2.  7.  0.]]
----------------------------------------------------------------------
Right-hand vector b: 
[[ -12.]
 [   6.]
 [-124.]
 [  29.]]
----------------------------------------------------------------------
Actual soluation x: 
[[6.]
 [5.]
 [5.]
 [9.]
 [2.]]
----------------------------------------------------------------------
Estimated soluation x_est: 
[ 6.699  5.183  3.012 10.415  0.   ]
and 
absolute diff|x-x_est| upto 10-th decimal place: 
[[0.69946333 0.81663685 2.98837209 4.41502683 6.        ]
 [1.69946333 0.18336315 1.98837209 5.41502683 5.        ]
 [1.69946333 0.18336315 1.98837209 5.41502683 5.        ]
 [2.30053667 3.81663685 5.98837209 1.41502683 9.        ]
 [4.69946333 3.18336315 1.01162791 8.41502683 2.        ]]
----------------------------------------------------------------------
