In [2]:
"""
-----------------------------------------------------------------------------
Assignment-2: Matrix computation exercise using python and numpy
-----------------------------------------------------------------------------
AUTHOR: Soumitra Samanta (soumitra.samanta@gm.rkmvu.ac.in)
-----------------------------------------------------------------------------
Package required:
Numpy: https://numpy.org/
Matplotlib: https://matplotlib.org
-----------------------------------------------------------------------------
"""

import numpy as np
from numpy.random import RandomState
from typing import Tuple

np.random.seed(42)  # To reproduce the random numbers





In [1]:
pip install numpy



[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: pip3.13 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


# Generate a random vector $x \in \mathbf{R}^{n}$ contains intergers between $[-l, l]$.
[3 points]

In [3]:
n = 10
l = 9
x = []

def random_vector(n,l):
  x=[]
  for i in range(n):
    x.append(np.random.randint(-l,l))
  return x
x=random_vector(n,l)

print('A random vector of size {}: ' .format(n))
print('-'*70)
print('x: {}' .format(x))
print('-'*70)

A random vector of size 10: 
----------------------------------------------------------------------
x: [-3, 5, 1, -2, -3, 1, 1, -6, -2, -7]
----------------------------------------------------------------------


# Write a function to calculate the 'dot' product between two vectors. Generate two random vectors $x, y \in \mathbf{R}^{n}$ contains intergers between $[-l, l]$ and find the dot product between $x$ and $y$ (your function should handle different order vectors). Check your result with the [numpy.dot](https://numpy.org/doc/stable/reference/generated/numpy.dot.html).
[5 points]




In [4]:
n = 10
l = 9
x = []
y = []

def vector_dot_product(
    x: np.array,
    y: np.array,
)->float:
    """
    Dot product between two vectors

    Inputs:
        - x: 1st vector
        - y: 2nd vector

    Output:
        - val: Dot product between x and y

    """

    val = []

    if len(x) == len(y):
      for i in range(len(x)):
        val.append(x[i]*y[i])
      val = sum(val)

      return val
    else:
      return "The order of two given vectors are different"

# np.random.seed(42)# for reproduce the random numbers
x = []
y = []
x=random_vector(n,l)
y=random_vector(n,l)

print('Two random vectors of size {} are:' .format(n))
print('-'*70)
print('x: {}\nand \ny: {}' .format(x, y))
print('-'*70)

val = vector_dot_product(x, y)
print('The dot product between x and y is: {}' .format(val))
print('-'*70)

val1 = np.dot(x, y)
print('The dot product between x and y using numpy.dot is: {}' .format(val1))
print('-'*70)

Two random vectors of size 10 are:
----------------------------------------------------------------------
x: [-8, 2, -4, -8, -9, 2, 2, 7, 0, 6]
and 
y: [5, 5, 2, -7, -5, -3, -1, -3, 8, -6]
----------------------------------------------------------------------
The dot product between x and y is: -2
----------------------------------------------------------------------
The dot product between x and y using numpy.dot is: -2
----------------------------------------------------------------------


# Generate a random matrix $A$ of size $m \times n$ contains intergers between $[-l, l]$.
[2 points]

In [4]:
m = 3
n = 5
l = 9
A = []

def random_matrix(m,n,l):
  A=[]
  for _ in range(m):
    A.append(random_vector(n,l))
  return A
A=random_matrix(m,n,l)

print('A random matrix of size {}x{} A:\n{}: ' .format(m, n, A))
print('-'*70)




A random matrix of size 3x5 A:
[[4, 8, -1, -8, 5], [-3, 2, -2, 5, -7], [4, 7, -6, 8, -2]]: 
----------------------------------------------------------------------


# Write a function to calculate the product of two matrices. Generate two random matrices $x \in \mathbf{R}^{m \times n}$ and $y \in \mathbf{R}^{n \times m}$ contains intergers between $[-l, l]$ and find the product of of $x$ and $y$ (your function should handle different order matrices). Check your result with the [numpy.matmul](https://numpy.org/doc/stable/reference/generated/numpy.matmul.html) or [numpy.dot](https://numpy.org/doc/stable/reference/generated/numpy.dot.html).

[10 points]




In [5]:
m = 3
n = 5
l = 9
x = []
y = []

def matrix_multiplication(
    x: np.array,
    y: np.array,
)->np.array:
    """
    Dot product between two vectors

    Inputs:
        - x: 1st matrix
        - y: 2nd matrix

    Output:
        - val: multiplication x and y

    """

    val = []

    rowx=len(x)
    colx=len(x[0])
    rowy=len(y)
    coly=len(y[0])
    if colx==rowy:
      for i in range(rowx):
        row=[]
        for j in range(coly):
          sum=0
          for k in range(colx):
            sum+=x[i][k]*y[k][j]
          row.append(sum)
        val.append(row)
      return val
    else:
      return "multiplication is not possible..."
    
# np.random.seed(42)# for reproduce the random numbers
A = []
B = []
A=random_matrix(m,n,l)
B=random_matrix(n,m,l)
print('Two random matrices are:')
print('A: \n{}\nand\nB: \n{}' .format(A, B))
print('-'*70)

val = matrix_multiplication(A, B)
print('The multiplication of A and B using my function is: \n{}' .format(val))
print('-'*70)

val1 = np.matmul(A,B)
print('The multiplication of A and B using numpy.matmul is: \n{}' .format(val1))
print('-'*70)

val1 = np.dot(A, B)
print('The multiplication of A and B using numpy.dot is: \n{}' .format(val1))
print('-'*70)

Two random matrices are:
A: 
[[-6, -8, -4, 0, -6], [8, 2, -8, 0, -6], [4, 6, 5, -2, 4]]
and
B: 
[[-2, 6, 3], [8, 5, 3], [-1, 5, 3], [-9, -3, -1], [-9, 2, -2]]
----------------------------------------------------------------------
The multiplication of A and B using my function is: 
[[6, -108, -42], [62, 6, 18], [17, 93, 39]]
----------------------------------------------------------------------
The multiplication of A and B using numpy.matmul is: 
[[   6 -108  -42]
 [  62    6   18]
 [  17   93   39]]
----------------------------------------------------------------------
The multiplication of A and B using numpy.dot is: 
[[   6 -108  -42]
 [  62    6   18]
 [  17   93   39]]
----------------------------------------------------------------------


# Implement elementary row operations and check your script with a random example.
[15 points]

In [6]:
import numpy as np
from typing import Tuple

def elementary_ops_interchange_rows(A: np.array, ith_row: int, jth_row: int) -> np.array:
    """
    Elementary row operation: interchange i-th and j-th rows
    """
    # convert 1-based input indices to 0-based internal indices
    i = ith_row - 1
    j = jth_row - 1

    A = A.copy()
    A[[i, j]] = A[[j, i]]
    return A


def elementary_ops_scale_row(A: np.array, ith_row: int, scalar_val: float) -> np.array:
    """
    Elementary row operation: Scaling i-th row with the scalar_val value
    """
    # convert 1-based input index to 0-based internal index
    i = ith_row - 1

    A = A.copy()
    A[i] = scalar_val * A[i]
    return A


def elementary_ops_change_row(A: np.array, ith_row: int, jth_row: int, scalar_val: float) -> np.array:
    """
    Elementary row operation: Change i-th based on i <- i + scalar_val * j
    """
    # convert 1-based input indices to 0-based internal indices
    i = ith_row - 1
    j = jth_row - 1

    A = A.copy()
    A[i] = A[i] + scalar_val * A[j]
    return A


def elementary_ops_interchange_rows_mult(A: np.array, ith_row: int, jth_row: int) -> Tuple[np.array, np.array]:
    """
    Elementary row operation: interchange i-th and j-th rows via matrix multiplication
    """
    # convert 1-based input indices to 0-based internal indices
    i = ith_row - 1
    j = jth_row - 1

    A = A.copy()
    m, n = A.shape
    I = np.eye(m)
    I[[i, j]] = I[[j, i]]
    A =matrix_multiplication(I,A)
    return A, I


def elementary_ops_scale_row_mult(A: np.array, ith_row: int, scalar_val: float) -> Tuple[np.array, np.array]:
    """
    Elementary row operation: Scaling i-th row with scalar_val via matrix multiplication
    """
    # convert 1-based input index to 0-based internal index
    i = ith_row - 1

    A = A.copy()
    m, n = A.shape
    I = np.eye(m)
    I[i, i] = scalar_val
    A =matrix_multiplication(I,A)
    return A, I


def elementary_ops_change_row_mult(A: np.array, ith_row: int, jth_row: int, scalar_val: float) -> Tuple[np.array, np.array]:
    """
    Elementary row operation: Change i-th based on i <- i + scalar_val * j via matrix multiplication
    """
    # convert 1-based input indices to 0-based internal indices
    i = ith_row - 1
    j = jth_row - 1

    A = A.copy()
    m, n = A.shape
    I = np.eye(m)
    I[i, j] = scalar_val
    A = matrix_multiplication(I,A)
    return A, I


# --------------------------------------------------------------------
# Testing Section
# --------------------------------------------------------------------
np.random.seed(42)  # for reproducibility
m = 3
n = 5
A = np.random.randint(1, 10, (m, n))

print("A random matrix A:\n", A)
print("-" * 70)

i = 1  # 1-based index (first row)
j = 2  # 1-based index (second row)
scalar = 3

E_ij = elementary_ops_interchange_rows(A.copy(), i, j)
print(f"Elementary row operation: interchange {i}-th and {j}-th rows on A:\n{A}\nis:\n{E_ij}")
print("-" * 70)

E_i = elementary_ops_scale_row(A.copy(), i, scalar)
print(f"Elementary row operation: Scaling {i}-th row with the {scalar} value on A:\n{A}\nis:\n{E_i}")
print("-" * 70)

E_ij_scalar = elementary_ops_change_row(A.copy(), i, j, scalar)
print(f"Elementary row operation: Change {i}-th based on {i} <- {i} + {scalar}*{j} on A:\n{A}\nis:\n{E_ij_scalar}")
print("-" * 70)

E_ij, I_ij = elementary_ops_interchange_rows_mult(A.copy(), i, j)
print(f"Elementary row operation (multiplication): interchange {i}-th and {j}-th rows on A:\n{A}\nis:\n{E_ij}\nand I_ij:\n{I_ij}")
print("-" * 70)

E_i, I_i = elementary_ops_scale_row_mult(A.copy(), i, scalar)
print(f"Elementary row operation (multiplication): Scaling {i}-th row with the {scalar} value on A:\n{A}\nis:\n{E_i}\nand I_i:\n{I_i}")
print("-" * 70)

E_ij_scalar, I_ij_scalar = elementary_ops_change_row_mult(A.copy(), i, j, scalar)
print(f"Elementary row operation (multiplication): Change {i}-th based on {i} <- {i} + {scalar}*{j} on A:\n{A}\nis:\n{E_ij_scalar}\nand I_ij(scale):\n{I_ij_scalar}")
print("-" * 70)


A random matrix A:
 [[7 4 8 5 7]
 [3 7 8 5 4]
 [8 8 3 6 5]]
----------------------------------------------------------------------
Elementary row operation: interchange 1-th and 2-th rows on A:
[[7 4 8 5 7]
 [3 7 8 5 4]
 [8 8 3 6 5]]
is:
[[3 7 8 5 4]
 [7 4 8 5 7]
 [8 8 3 6 5]]
----------------------------------------------------------------------
Elementary row operation: Scaling 1-th row with the 3 value on A:
[[7 4 8 5 7]
 [3 7 8 5 4]
 [8 8 3 6 5]]
is:
[[21 12 24 15 21]
 [ 3  7  8  5  4]
 [ 8  8  3  6  5]]
----------------------------------------------------------------------
Elementary row operation: Change 1-th based on 1 <- 1 + 3*2 on A:
[[7 4 8 5 7]
 [3 7 8 5 4]
 [8 8 3 6 5]]
is:
[[16 25 32 20 19]
 [ 3  7  8  5  4]
 [ 8  8  3  6  5]]
----------------------------------------------------------------------
Elementary row operation (multiplication): interchange 1-th and 2-th rows on A:
[[7 4 8 5 7]
 [3 7 8 5 4]
 [8 8 3 6 5]]
is:
[[np.float64(3.0), np.float64(7.0), np.float64(8.0), np

# Implement elementary column operations and check your script with random example
[10 points]

In [9]:
import numpy as np
from typing import Tuple

# ==========================================================
#  Elementary Column Operations
# ==========================================================

def elementary_ops_interchange_cols(A: np.array, ith_col: int, jth_col: int) -> np.array:
    """
    Elementary column operation: interchange i-th and j-th columns
    """
    # convert 1-based input indices to 0-based internal indices
    i = ith_col - 1
    j = jth_col - 1

    A = A.copy()
    A[:, [i, j]] = A[:, [j, i]]
    return A


def elementary_ops_scale_col(A: np.array, ith_col: int, scalar_val: float) -> np.array:
    """
    Elementary column operation: scale i-th column with the scalar_val
    """
    # convert 1-based input index to 0-based internal index
    i = ith_col - 1

    A = A.copy()
    A[:, i] = scalar_val * A[:, i]
    return A


def elementary_ops_change_col(A: np.array, ith_col: int, jth_col: int, scalar_val: float) -> np.array:
    """
    Elementary column operation: change i-th column based on i <- i + scalar_val * j
    """
    # convert 1-based input indices to 0-based internal indices
    i = ith_col - 1
    j = jth_col - 1

    A = A.copy()
    A[:, i] = A[:, i] + scalar_val * A[:, j]
    return A


def elementary_ops_interchange_cols_mult(A: np.array, ith_col: int, jth_col: int) -> Tuple[np.array, np.array]:
    """
    Elementary column operation: interchange i-th and j-th columns via matrix multiplication
    """
    # convert 1-based input indices to 0-based internal indices
    i = ith_col - 1
    j = jth_col - 1

    A = A.copy()
    m, n = A.shape
    I = np.eye(n)
    I[:, [i, j]] = I[:, [j, i]]  # swap columns in identity
    A = A @ I
    return A, I


def elementary_ops_scale_col_mult(A: np.array, ith_col: int, scalar_val: float) -> Tuple[np.array, np.array]:
    """
    Elementary column operation: scale i-th column with scalar_val via matrix multiplication
    """
    # convert 1-based input index to 0-based internal index
    i = ith_col - 1

    A = A.copy()
    m, n = A.shape
    I = np.eye(n)
    I[i, i] = scalar_val
    A = A @ I
    return A, I


def elementary_ops_change_col_mult(A: np.array, ith_col: int, jth_col: int, scalar_val: float) -> Tuple[np.array, np.array]:
    """
    Elementary column operation: change i-th column based on i <- i + scalar_val * j via matrix multiplication
    """
    # convert 1-based input indices to 0-based internal indices
    i = ith_col - 1
    j = jth_col - 1

    A = A.copy()
    m, n = A.shape
    I = np.eye(n)
    I[j, i] = scalar_val  # modify column of identity for column operation
    A = A @ I
    return A, I


# ==========================================================
#  Testing Section
# ==========================================================
np.random.seed(42)  # for reproducibility
m = 3
n = 5
A = np.random.randint(1, 10, (m, n))

print("A random matrix A:\n", A)
print("-" * 70)

i = 1  # 1-based index (first column)
j = 2  # 1-based index (second column)
scalar = 3

# ---- Direct column operations ----
E_ij = elementary_ops_interchange_cols(np.copy(A), i, j)
print(f"Elementary col operation: interchange {i}-th and {j}-th cols on A:\n{A}\nis:\n{E_ij}")
print("-" * 70)

E_i = elementary_ops_scale_col(np.copy(A), i, scalar)
print(f"Elementary col operation: Scaling {i}-th col with the {scalar} value on A:\n{A}\nis:\n{E_i}")
print("-" * 70)

E_ij_scalar = elementary_ops_change_col(np.copy(A), i, j, scalar)
print(f"Elementary col operation: Change {i}-th based on {i} <- {i} + {scalar}*{j} on A:\n{A}\nis:\n{E_ij_scalar}")
print("-" * 70)

# ---- Column operations via matrix multiplication ----
E_ij, I_ij = elementary_ops_interchange_cols_mult(np.copy(A), i, j)
print(f"Elementary col operation (multiplication): interchange {i}-th and {j}-th cols on A:\n{A}\nis:\n{E_ij}\nand I_ij:\n{I_ij}")
print("-" * 70)

E_i, I_i = elementary_ops_scale_col_mult(np.copy(A), i, scalar)
print(f"Elementary col operation (multiplication): Scaling {i}-th col with the {scalar} value on A:\n{A}\nis:\n{E_i}\nand I_i:\n{I_i}")
print("-" * 70)

E_ij_scalar, I_ij_scalar = elementary_ops_change_col_mult(np.copy(A), i, j, scalar)
print(f"Elementary col operation (multiplication): Change {i}-th based on {i} <- {i} + {scalar}*{j} on A:\n{A}\nis:\n{E_ij_scalar}\nand I_ij_scalar:\n{I_ij_scalar}")
print("-" * 70)


A random matrix A:
 [[7 4 8 5 7]
 [3 7 8 5 4]
 [8 8 3 6 5]]
----------------------------------------------------------------------
Elementary col operation: interchange 1-th and 2-th cols on A:
[[7 4 8 5 7]
 [3 7 8 5 4]
 [8 8 3 6 5]]
is:
[[4 7 8 5 7]
 [7 3 8 5 4]
 [8 8 3 6 5]]
----------------------------------------------------------------------
Elementary col operation: Scaling 1-th col with the 3 value on A:
[[7 4 8 5 7]
 [3 7 8 5 4]
 [8 8 3 6 5]]
is:
[[21  4  8  5  7]
 [ 9  7  8  5  4]
 [24  8  3  6  5]]
----------------------------------------------------------------------
Elementary col operation: Change 1-th based on 1 <- 1 + 3*2 on A:
[[7 4 8 5 7]
 [3 7 8 5 4]
 [8 8 3 6 5]]
is:
[[19  4  8  5  7]
 [24  7  8  5  4]
 [32  8  3  6  5]]
----------------------------------------------------------------------
Elementary col operation (multiplication): interchange 1-th and 2-th cols on A:
[[7 4 8 5 7]
 [3 7 8 5 4]
 [8 8 3 6 5]]
is:
[[4. 7. 8. 5. 7.]
 [7. 3. 8. 5. 4.]
 [8. 8. 3. 6. 5.]]


# Implement row and column sweep out and check your script with random example
[10 points]

In [9]:
import numpy as np
from typing import Tuple

# ---------------------- Helper ----------------------
def matrix_multiplication(A: np.array, B: np.array) -> np.array:
    """
    Matrix multiplication using numpy
    """
    return A @ B

# ---------------------- Sweep out row ----------------------
def sweep_out_row(A: np.array, pivot_element: Tuple[int,int]) -> np.array:
    """
    Row sweep-out: zero all elements in pivot row except pivot, which becomes 1.
    pivot_element: 1-based (row, col)
    """
    A = A.astype(float).copy()
    p, q = pivot_element
    p -= 1
    q -= 1
    pivot_val = A[p, q]

    for j in range(A.shape[1]):
        if j != q:
            A[:, j] = pivot_val * A[:, j] - A[p, j] * A[:, q]

    # Normalize pivot row to 1
    A[p, :] = A[p, :] / pivot_val
    return A

def sweep_out_row_mult(A: np.array, pivot_element: Tuple[int,int]) -> Tuple[np.array, np.array]:
    """
    Row sweep-out using matrix multiplication.
    Returns transformed matrix and elementary operation matrix.
    Pivot becomes 1.
    """
    A = A.astype(float).copy()
    m, n = A.shape
    p, q = pivot_element
    p -= 1
    q -= 1
    pivot_val = A[p, q]

    E_ops = np.eye(m)
    for i in range(m):
        if i != p:
            E_ops[i, :] = pivot_val * E_ops[i, :] - A[i, q] * E_ops[p, :]

    A_new = matrix_multiplication(E_ops, A)

    # Normalize pivot row to 1
    pivot_in_new = A_new[p, q]
    A_new[p, :] = A_new[p, :] / pivot_in_new
    return A_new, E_ops

# ---------------------- Sweep out column ----------------------
def sweep_out_col(A: np.array, pivot_element: Tuple[int,int]) -> np.array:
    """
    Column sweep-out: zero all elements in pivot column except pivot, which becomes 1.
    pivot_element: 1-based (row, col)
    """
    A = A.astype(float).copy()
    p, q = pivot_element
    p -= 1
    q -= 1
    pivot_val = A[p, q]

    for i in range(A.shape[0]):
        if i != p:
            A[i, :] = pivot_val * A[i, :] - A[i, q] * A[p, :]

    # Normalize pivot column to 1
    A[:, q] = A[:, q] / pivot_val
    return A

def sweep_out_col_mult(A: np.array, pivot_element: Tuple[int,int]) -> Tuple[np.array, np.array]:
    """
    Column sweep-out using matrix multiplication.
    Returns transformed matrix and elementary operation matrix.
    Pivot becomes 1.
    """
    A = A.astype(float).copy()
    m, n = A.shape
    p, q = pivot_element
    p -= 1
    q -= 1
    pivot_val = A[p, q]

    E_ops = np.eye(n)
    for j in range(n):
        if j != q:
            E_ops[:, j] = pivot_val * E_ops[:, j] - A[p, j] * E_ops[:, q]

    A_new = matrix_multiplication(A, E_ops)

    # Normalize pivot column to 1
    pivot_in_new = A_new[p, q]
    A_new[:, q] = A_new[:, q] / pivot_in_new
    return A_new, E_ops

# ---------------------- Example run ----------------------
np.random.seed(42)
l = 5
m, n = 3, 5
A = np.random.randint(-l, l+1, size=(m, n))

print("Random matrix A:\n", A)
print("-"*70)

pivot_1_based = (1, 2)  # 1st row, 2nd column

# Row sweep
E_row = sweep_out_row(np.copy(A), pivot_1_based)
print(f"Row sweep out about pivot {pivot_1_based} :\n{E_row}")
print("-"*70)

# Row sweep matrix form
E_row_mult, E_ops_row = sweep_out_row_mult(np.copy(A), pivot_1_based)
print(f"Row sweep (matrix form) about pivot {pivot_1_based}:\n{E_row_mult}")
print("Elementary row operations matrix E_ops:\n", E_ops_row)
print("-"*70)

# Column sweep
E_col = sweep_out_col(np.copy(A), pivot_1_based)
print(f"Column sweep out about pivot {pivot_1_based}:\n{E_col}")
print("-"*70)

# Column sweep matrix form
E_col_mult, E_ops_col = sweep_out_col_mult(np.copy(A), pivot_1_based)
print(f"Column sweep (matrix form) about pivot {pivot_1_based}:\n{E_col_mult}")
print("Elementary column operations matrix E_ops:\n", E_ops_col)
print("-"*70)


Random matrix A:
 [[ 1 -2  5  2 -1]
 [ 1  4 -3  1  5]
 [ 5  2 -1 -2  2]]
----------------------------------------------------------------------
Row sweep out about pivot (1, 2) :
[[ -0.   1.  -0.  -0.  -0.]
 [ -6.   4. -14. -10.  -6.]
 [-12.   2.  -8.   0.  -2.]]
----------------------------------------------------------------------
Row sweep (matrix form) about pivot (1, 2):
[[ -0.5   1.   -2.5  -1.    0.5]
 [ -6.    0.  -14.  -10.   -6. ]
 [-12.    0.   -8.    0.   -2. ]]
Elementary row operations matrix E_ops:
 [[ 1.  0.  0.]
 [-4. -2. -0.]
 [-2. -0. -2.]]
----------------------------------------------------------------------
Column sweep out about pivot (1, 2):
[[  1.   1.   5.   2.  -1.]
 [ -6.  -0. -14. -10.  -6.]
 [-12.  -0.  -8.   0.  -2.]]
----------------------------------------------------------------------
Column sweep (matrix form) about pivot (1, 2):
[[  0.   1.   0.   0.   0.]
 [ -6.  -2. -14. -10.  -6.]
 [-12.  -1.  -8.   0.  -2.]]
Elementary column operations matrix E_

# Implement echelon form of a matrix $A$ 
[20 points]

In [10]:
import numpy as np

def reduced_echelon_form(
    A: np.array
)-> np.array:
    """Reduction to echelon form of a matrix.

    Inputs:
        - A: Given matrix

    Output:
        - A: Echelon form of A
    """

    A = A.copy().astype(float)
    m, n = A.shape
    pivot_row = 0  # track current pivot row

    for pivot_col in range(n):
        if pivot_row >= m:
            break

        # Find pivot: first non-zero in this column
        pivot_found = False
        for r in range(pivot_row, m):
            if abs(A[r, pivot_col]) > 1e-12:
                if r != pivot_row:
                    A[[pivot_row, r]] = A[[r, pivot_row]]  # swap rows
                pivot_found = True
                break

        if not pivot_found:
            continue

        # Normalize pivot row
        pivot_val = A[pivot_row, pivot_col]
        A[pivot_row, :] = A[pivot_row, :] / pivot_val

        # Eliminate entries above and below pivot
        for r in range(m):
            if r != pivot_row:
                factor = A[r, pivot_col]
                A[r, :] = A[r, :] - factor * A[pivot_row, :]

        pivot_row += 1

    return A


# ===============================================================
# Example Test
# ===============================================================
np.random.seed(42)
A = np.array([
    [0, 0, 0, 0, 5],
    [0, 2, -1, 3, -2],
    [0, -4, 2, -6, 4],
    [0, 6, -3, 8, 1]
]).astype(float)

print('A random matrix A:\n{}'.format(A))
print('-'*70)

EF_A = reduced_echelon_form(A)
print('The reduced echelon form of A:\n{}'.format(np.round(EF_A, 3)))
print('-'*70)


A random matrix A:
[[ 0.  0.  0.  0.  5.]
 [ 0.  2. -1.  3. -2.]
 [ 0. -4.  2. -6.  4.]
 [ 0.  6. -3.  8.  1.]]
----------------------------------------------------------------------
The reduced echelon form of A:
[[ 0.   1.  -0.5  0.   0. ]
 [ 0.   0.   0.   1.   0. ]
 [ 0.   0.   0.   0.   1. ]
 [ 0.   0.   0.   0.   0. ]]
----------------------------------------------------------------------


# [<font color='red'>BONUS</font>] Implement reduction to upper triangular form of a matrix $A$
[5 points]

In [11]:
import numpy as np

def reduced_upper_triangular_form(A: np.array) -> np.array:
    """
    Reduction to upper triangular form of a square matrix (Gaussian elimination).
    
    Inputs:
        - A: Given square matrix
        
    Output:
        - A: Upper triangular form of A
    """
    A = A.astype(float).copy()
    n = A.shape[0]

    for i in range(n):
        # Find pivot (non-zero) in column i at or below row i
        pivot = i
        while pivot < n and A[pivot, i] == 0:
            pivot += 1
        if pivot == n:
            continue  # No pivot found in this column, move to next column

        # Swap rows if necessary
        if pivot != i:
            A[[i, pivot]] = A[[pivot, i]]

        # Eliminate entries below the pivot
        for r in range(i + 1, n):
            if A[r, i] != 0:
                factor = A[r, i] / A[i, i]
                A[r, i:] = A[r, i:] - factor * A[i, i:]

    return A


# ==========================================================
# Test Section
# ==========================================================
np.random.seed(42)  # for reproducibility
n = 5
A = np.random.randint(1, 10, (n, n)).astype(float)

print("A random matrix A:\n", A)
print("-" * 70)

UT_A = reduced_upper_triangular_form(A)
print("The reduced upper triangular form of A:\n", np.round(UT_A, 3))
print("-" * 70)


A random matrix A:
 [[7. 4. 8. 5. 7.]
 [3. 7. 8. 5. 4.]
 [8. 8. 3. 6. 5.]
 [2. 8. 6. 2. 5.]
 [1. 6. 9. 1. 3.]]
----------------------------------------------------------------------
The reduced upper triangular form of A:
 [[ 7.     4.     8.     5.     7.   ]
 [ 0.     5.286  4.571  2.857  1.   ]
 [ 0.     0.    -9.108 -1.568 -3.649]
 [ 0.     0.     0.    -2.754  2.591]
 [ 0.    -0.     0.     0.    -3.297]]
----------------------------------------------------------------------
