In [1]:
"""
-----------------------------------------------------------------------------
Assignment-4: Matrix computation exercise using python and numpy
-----------------------------------------------------------------------------
AUTHOR: Soumitra Samanta (soumitra.samanta@gm.rkmvu.ac.in)
-----------------------------------------------------------------------------
Package required:
Numpy: https://numpy.org/
Matplotlib: https://matplotlib.org
-----------------------------------------------------------------------------
"""

import numpy as np
from numpy.random import RandomState
from assignment_5_matrix_computation_exc import *

# for auto-reloading extenrnal modules
# see http://stackoverflow.com/questions/1907993/autoreload-of-modules-in-ipython
%load_ext autoreload
%autoreload 2


# Please check the file <font color='red'>assignment_5_matrix_computation.py</font> and fillup all the functions implementation from Assignment-2, Assignment-3 and Assignment-4
-----------------------------------------------------------------------------

# Use a suitable matrix reduced form (RCF, UTF, NF, HCF...) to find the $determinant$ of a square matrix of order $n$. You generate a random random square matrix of different order  and check your results with the [numpy.linalg.det](https://numpy.org/doc/stable/reference/generated/numpy.linalg.det.html). Implement your funtion <font color='red'>determinant_matrix</font> started at <font color='red'>line no 797</font> in <font color='red'>assignment_5_matrix_computation.py</font> file in appropriate location. You'll find <font color='red'>assignment_5_matrix_computation.py</font> within this folder.
[10 points]

In [2]:
import numpy as np
from assignment_5_matrix_computation_exc import *

In [3]:
# Now test your code
np.random.seed(42)
l = 9
n = 5
error_decimal = 10

A = np.random.randint(-l, l+1, (n, n)) 
print('A random matrices A:\n{}' .format(A))
print('-'*70)

det_value = determinant_matrix(A)
det_value_numpy = np.linalg.det(A)

print('The determinant value of A using my implementarion is:\n{}\nand\nUsing numpy: \n{}\nError: {} '
      .format(det_value, det_value_numpy, det_value - det_value_numpy))
print('-'*70)


A random matrices A:
[[-3  5  1 -2 -3]
 [ 9  1  1 -6 -2]
 [-7 -8  2 -4 -8]
 [-9  2  2  7  0]
 [ 6  5  5  9  2]]
----------------------------------------------------------------------
The determinant value of A using my implementarion is:
4367.999999999986
and
Using numpy: 
4367.999999999998
Error: -1.1823431123048067e-11 
----------------------------------------------------------------------


# Implement Cramer's rule to find a soluation of a system $Ax=b$. Where $A$ is a matrix of order $n \times n$. You have to generate a random system of linear equation ($n$-equations with $n$ unknowns) and check your results. Use your previous funtion <font color='red'>generate_random_linear_system</font> to generate the linear system and implement <font color='red'>soln_n_equations_n_unknowns_cramers_rule</font> started at <font color='red'>line no 825</font> in <font color='red'>assignment_5_matrix_computation.py</font> file in appropriate location. You'll find <font color='red'>assignment_5_matrix_computation.py</font> within this folder.
[10 points]

In [4]:
np.random.seed(42)# for reproduce the random numbers
l = 9
n = 5
error_decimal = 10

A, b, x = generate_random_linear_system(n, n)
print('The coefficient matrix A: \n{}' .format(A))
print('-'*70) 
print('Right-hand vector b: \n{}' .format(b))
print('-'*70)
print('Actual soluation x: \n{}' .format(x))
print('-'*70)


x_est = soln_n_equations_n_unknowns_cramers_rule(A, b)        
print('Estimated soluation x_est: \n{}\nand \nabsolute diff|x-x_est| upto {}-th decimal place: \n{}' .format(np.round(x_est, 3), error_decimal, np.round(np.abs(x-x_est), error_decimal)))
print('-'*70)      

The coefficient matrix A: 
[[-3.  5.  1. -2. -3.]
 [ 9.  1.  1. -6. -2.]
 [-7. -8.  2. -4. -8.]
 [-9.  2.  2.  7.  0.]
 [ 6.  5.  5.  9.  2.]]
----------------------------------------------------------------------
Right-hand vector b: 
[[ 14.]
 [-39.]
 [127.]
 [ 50.]
 [-51.]]
----------------------------------------------------------------------
Actual soluation x: 
[[-7.]
 [-5.]
 [ 9.]
 [-3.]
 [-1.]]
----------------------------------------------------------------------
Estimated soluation x_est: 
[[-7.]
 [-5.]
 [ 9.]
 [-3.]
 [-1.]]
and 
absolute diff|x-x_est| upto 10-th decimal place: 
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]]
----------------------------------------------------------------------
